WebApp/Models/Feedback.cs
using System;
using System.Collections.Generic;

namespace WebApp.Models
{
    public partial class Feedback
    {
        public int FeedbackId { get; set; }
        public string? FeedbackContent { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }
        public int? InsuranceId { get; set; }
        public int? CustomerId { get; set; }

        public virtual Customer? Customer { get; set; }
        public virtual Insurance? Insurance { get; set; }
    }
}

WebApp/Areas/Admin/Controllers/FeedbackController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Models;
using X.PagedList;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FeedbackController : Controller
    {
        private readonly InsuranceOnlineContext db = new InsuranceOnlineContext();

        // GET: Admin/Feedback
        public async Task<IActionResult> Index(int page=1, int limit=10)
        {
            var insuranceOnlineContext = db.Feedbacks.Include(f => f.Customer).Include(f => f.Insurance);
            var result = await insuranceOnlineContext.ToPagedListAsync(page,limit);
            ViewBag.TotalPage = Math.Ceiling((decimal)db.Feedbacks.ToList().Count/limit);
            ViewBag.CurrentPage = page;
            if (limit != 10)
            {
                ViewBag.Limit = limit;
            }
            return View(result);
        }

        // GET: Admin/Feedback/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || db.Feedbacks == null)
            {
                return NotFound();
            }

            var feedback = await db.Feedbacks
                .Include(f => f.Customer)
                .Include(f => f.Insurance)
                .FirstOrDefaultAsync(m => m.FeedbackId == id);
            if (feedback == null)
            {
                return NotFound();
            }

            return View(feedback);
        }

        // GET: Admin/Feedback/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(db.Customers, "Id", "Username");
            ViewData["InsuranceId"] = new SelectList(db.Insurances, "Id", "Name");
            return View();
        }

        // POST: Admin/Feedback/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("FeedbackId,FeedbackContent,CreatedAt,UpdatedAt,InsuranceId,CustomerId")] Feedback feedback)
        {
            if (ModelState.IsValid)
            {
                db.Add(feedback);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(db.Customers, "Id", "Username", feedback.CustomerId);
            ViewData["InsuranceId"] = new SelectList(db.Insurances, "Id", "Name", feedback.InsuranceId);
            return View(feedback);
        }

        // GET: Admin/Feedback/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || db.Feedbacks == null)
            {
                return NotFound();
            }

            var feedback = await db.Feedbacks.FindAsync(id);
            if (feedback == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(db.Customers, "Id", "Username", feedback.CustomerId);
            ViewData["InsuranceId"] = new SelectList(db.Insurances, "Id", "Name", feedback.InsuranceId);
            return View(feedback);
        }

        // POST: Admin/Feedback/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("FeedbackId,FeedbackContent,CreatedAt,UpdatedAt,InsuranceId,CustomerId")] Feedback feedback)
        {
            if (id != feedback.FeedbackId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(feedback);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FeedbackExists(feedback.FeedbackId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(db.Customers, "Id", "Username", feedback.CustomerId);
            ViewData["InsuranceId"] = new SelectList(db.Insurances, "Id", "Name", feedback.InsuranceId);
            return View(feedback);
        }

        // GET: Admin/Feedback/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || db.Feedbacks == null)
            {
                return NotFound();
            }

            var feedback = await db.Feedbacks
                .Include(f => f.Customer)
                .Include(f => f.Insurance)
                .FirstOrDefaultAsync(m => m.FeedbackId == id);
            if (feedback == null)
            {
                return NotFound();
            }

            return View(feedback);
        }

        // POST: Admin/Feedback/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (db.Feedbacks == null)
            {
                return Problem("Entity set 'InsuranceOnlineContext.Feedbacks'  is null.");
            }
            var feedback = await db.Feedbacks.FindAsync(id);
            if (feedback != null)
            {
                db.Feedbacks.Remove(feedback);
            }
            
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FeedbackExists(int id)
        {
          return (db.Feedbacks?.Any(e => e.FeedbackId == id)).GetValueOrDefault();
        }
    }
}

WebApp/Controllers/FeedbacksController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Models;
using X.PagedList;

namespace WebApp.Controllers
{
    public class FeedbacksController : Controller
    {
        private InsuranceOnlineContext db = new InsuranceOnlineContext();
        public IActionResult Index(int page=1,int limit=10)
        {
            if (TempData["msg"] != null)
            {
                ViewBag.Msg = TempData["msg"].ToString();
            }
            var uid = HttpContext.Session.GetInt32("user_id");
            var list = db.Feedbacks
                .Where(x=>x.CustomerId==uid)
                .Include(x => x.Insurance).ThenInclude(x=>x.Category)
                .Include(x => x.Customer)
                .OrderBy(x => x.FeedbackId)

                .ToList();
            var result = list.ToPagedList(page,limit);
            
            ViewBag.CurrentPage = page;
            ViewBag.TotalPage = Math.Ceiling((decimal)db.Feedbacks.Where(x=>x.CustomerId==uid).ToList().Count/limit);
            return View(result);
        }

        [HttpGet]
        public ActionResult Create()
        {
            ViewData["InsuranceId"] = new SelectList(db.Insurances, "Id", "Name");
            return View();
        }

        [HttpPost]
        public ActionResult Create(Feedback e)
        {
            db.Feedbacks.Add(e);
            var stt = db.SaveChanges()>0;
            if (stt)
            {
                TempData["msg"] = "Save successfully!";
            }
            else
            {
                TempData["msg"] = "Save Failed!";
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var e = db.Feedbacks.FirstOrDefault(x=>x.FeedbackId==id);
            if(e!=null)
            {
                ViewData["InsuranceId"] = new SelectList(db.Insurances, "Id", "Name",e.InsuranceId);
                return View(e);
            }              
            else
                return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult Edit(Feedback e)
        {
            var o = db.Feedbacks.FirstOrDefault(x=>x.FeedbackId==e.FeedbackId);
            if (o != null)
            {
                if (o.InsuranceId != e.InsuranceId)
                    o.InsuranceId = e.InsuranceId;
                if(o.FeedbackContent!=e.FeedbackContent)
                    o.FeedbackContent = e.FeedbackContent;
                o.UpdatedAt = DateTime.Now;
                var stt = db.SaveChanges() > 0;
                if (stt)
                {
                    TempData["msg"] = "Save successfully!";
                }
                else
                {
                    TempData["msg"] = "Save Failed!";
                }
            }
            
            return RedirectToAction(nameof(Index));
        }
    }
}

WebApp/Views/Feedbacks/Create.cshtml
@using Microsoft.AspNetCore.Http;
@model WebApp.Models.Feedback

@{
    ViewData["Title"] = "Create Feedback";
    var uid = Context.Session.GetInt32("user_id");
    var name = new InsuranceOnlineContext().Customers.FirstOrDefault(x=>x.Id==uid).Username;
}


<div class="section banner-page about">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="title-page">Account</div>
                <ol class="breadcrumb">
                    <li><a href="#">Create a feedback</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>


<div class="section contact">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-md-4 col-md-push-8">
                <div class="widget download">
                    <a href="#" class="btn btn-secondary btn-block btn-sidebar"><span class="fa  fa-file-pdf-o"></span> Company Brochure</a>
                </div>

                <partial name="~/Views/Shared/_contact.cshtml" />

            </div>
            <div class="col-sm-8 col-md-8 col-md-pull-4">
                <div class="content">
                    <h3 class="section-heading-2">
                        Your feedback here
                    </h3>
                    <form asp-action="Create">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input type="hidden" value="@uid" name="CustomerId" />
                        <div class="row">
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Your name</label>
                                    <input type="text" class="form-control" id="p_name" value="@name" placeholder="Full Name...">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="InsuranceId" class="control-label">Insurance</label>
                            <select asp-for="InsuranceId" class="form-control" asp-items="ViewBag.InsuranceId"></select>
                        </div>
                        <h3 class="section-heading-2">
                            What We Need to Know
                        </h3>
                        <div class="form-group">
                            <label asp-for="FeedbackContent" class="control-label"></label>
                            <textarea asp-for="FeedbackContent" rows="6" class="form-control"></textarea>
                            <span asp-validation-for="FeedbackContent" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div id="success"></div>
                            <button type="submit" class="btn btn-secondary">Send</button>
                        </div>
                    </form>
                    <div class="margin-bottom-50"></div>
                </div>
            </div>

        </div>

    </div>
</div>

WebApp/Views/Feedbacks/Edit.cshtml
@using Microsoft.AspNetCore.Http;
@model WebApp.Models.Feedback

@{
    ViewData["Title"] = "Create Feedback";
    var uid = Context.Session.GetInt32("user_id");
    var name = new InsuranceOnlineContext().Customers.FirstOrDefault(x=>x.Id==uid).Username;
}


<div class="section banner-page about">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="title-page">Account</div>
                <ol class="breadcrumb">
                    <li><a href="#">Feedback detail</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>


<div class="section contact">
    <div class="container">
        <div class="row">
            <div class="col-sm-4 col-md-4 col-md-push-8">
                <div class="widget download">
                    <a href="#" class="btn btn-secondary btn-block btn-sidebar"><span class="fa  fa-file-pdf-o"></span> Company Brochure</a>
                </div>

                <partial name="~/Views/Shared/_contact.cshtml" />

            </div>
            <div class="col-sm-8 col-md-8 col-md-pull-4">
                <div class="content">
                    <h3 class="section-heading-2">
                        Your feedback here
                    </h3>
                    <form asp-action="Edit">
                        <div asp-validation-summary="All" class="text-danger"></div>
                        <input type="hidden" value="@uid" name="CustomerId" />
                        <input type="hidden" value="@Model.FeedbackId" name="FeedbackId" />
                        <div class="row">
                            <div class="col-sm-6 col-md-6">
                                <div class="form-group">
                                    <label class="control-label">Your name</label>
                                    <input type="text" class="form-control" id="p_name" value="@name" placeholder="Full Name...">
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label asp-for="InsuranceId" class="control-label">Insurance</label>
                            <select asp-for="InsuranceId" class="form-control" asp-items="ViewBag.InsuranceId"></select>
                        </div>
                        <h3 class="section-heading-2">
                            What We Need to Know
                        </h3>
                        <div class="form-group">
                            <label asp-for="FeedbackContent" class="control-label"></label>
                            <textarea asp-for="FeedbackContent" rows="6" class="form-control"></textarea>
                            <span asp-validation-for="FeedbackContent" class="text-danger"></span>
                        </div>
                        <div class="form-group">
                            <div id="success"></div>
                            <button type="submit" class="btn btn-secondary">Send</button>
                        </div>
                    </form>
                    <div class="margin-bottom-50"></div>
                </div>
            </div>

        </div>

    </div>
</div>

WebApp/Views/Feedbacks/Index.cshtml
@using WebApp.Models;
@using X.PagedList;
@model IPagedList<Feedback>

@{
    ViewBag.Title = "Your feedbacks list";
}

<!-- BANNER -->
<div class="section banner-page about">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <div class="title-page">Account</div>
                <ol class="breadcrumb">
                    <li><a href="#">Feedback List</a></li>
                </ol>
            </div>
        </div>
    </div>
</div>

<!-- CTA -->
<div class="section cta">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-7 col-md-offset-1">
                <h3 class="cta-desc">Feedback to help make our service be better</h3>
            </div>
            <div class="col-sm-12 col-md-3">
                <a href="@Url.Action("Create","Feedbacks")" title="" class="btn btn-orange-cta pull-right btn-view-all">Create A Feedback</a>
            </div>

        </div>
    </div>
</div>

<!-- Team -->
<div class="section about section-border">
    <div class="container">
        <div class="row">
            <div class="col-sm-12 col-md-12">
                <h2 class="section-heading">
                    Your feedback
                </h2>
            </div>
        </div>
        <div class="row">

            @{
                if (Model != null && Model.Count > 0)
                {
                    foreach (var item in Model)
                    {
                        <div class="col-sm-6 col-md-6">
                            <div class="box-team">
                                <div class="box-image">
                                    <img src="@item.Insurance.Image" alt="">
                                </div>
                                <div class="body-content">
                                    <div class="people">@item.Insurance.Category.CategoryName</div>
                                    <div class="position">@item.Insurance.Name</div>
                                    <div class="detail-text">
                                        <span class="fa fa-file-text"> </span> Content:
                                        <a href="@Url.Action("Edit","Feedbacks",new {id=item.FeedbackId})"> View</a>
                                    </div>
                                    <div class="detail-text">
                                        <span class="fa fa-bookmark-o"></span>
                                        Posted at: @item.CreatedAt.Value.ToString("d")
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                }
                else
                {
                    <h3>You didn't post any feedbacks</h3>
                }
            }

        </div>

        <div class="row">
            <div class="col-sm-12 col-md-12">
                <ul class="pagination">
                    @{
                        var list = ViewBag.TotalPage;
                        if (list != null)
                        {
                            var c = ViewBag.Page;
                            for (int i = 1; i <= list; i++)
                            {
                                <li class="@((i==c)?"active":"")">
                                    <a href="@Url.Action("","Feedbacks", new {page=i})">@i</a>
                                </li>
                            }
                        }
                    }
                </ul>
            </div>
        </div>
    </div>
</div>