WebApp/Models/Contract.cs
using System;
using System.Collections.Generic;

namespace WebApp.Models
{
    public partial class Contract
    {
        public Contract()
        {
            Payments = new HashSet<Payment>();
        }

        public int Id { get; set; }
        public string? Beneficiary { get; set; }
        public int Duration { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? ExpiredAt { get; set; }
        public int? CustomerId { get; set; }
        public int? InsuranceId { get; set; }
        public bool? Status { get; set; }
        public decimal Total { get; set; }

        public virtual Customer? Customer { get; set; }
        public virtual Insurance? Insurance { get; set; }
        public virtual ICollection<Payment> Payments { get; set; }
    }
}

WebApp/Areas/Admin/Controllers/ContractController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApp.Models;
using X.PagedList;

namespace WebApp.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContractController : Controller
    {
        private readonly InsuranceOnlineContext db = new InsuranceOnlineContext();


        // GET: Admin/Contract
        public async Task<IActionResult> Index(int page=1, int limit =10)
        {
            ViewBag.CurrentPage = page;
            ViewBag.TotalPage = Math.Ceiling((decimal)db.Contracts.ToList().Count / limit);
            if (limit != 10)
            {
                ViewBag.Limit = limit;
            }
            var insuranceOnlineContext = db.Contracts.Include(c => c.Customer).Include(c => c.Insurance);
            var result = await insuranceOnlineContext.ToPagedListAsync(page, limit);
            return db.Contracts != null ?
                          View(result) :
                          Problem("Entity set 'InsuranceOnlineContext.Contracts'  is null.");
        }

        // GET: Admin/Contract/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || db.Contracts == null)
            {
                return NotFound();
            }

            var contract = await db.Contracts
                .Include(c => c.Customer)
                .Include(c => c.Insurance)
                .Include(x=>x.Payments).ThenInclude(x=>x.PaymentDetails)
                .FirstOrDefaultAsync(m => m.Id == id);

            if (contract == null)
            {
                return NotFound();
            }
            return View(contract);
        }

        // GET: Admin/Contract/Create
        public IActionResult Create()
        {
            ViewData["CustomerId"] = new SelectList(db.Customers, "Id", "Username");
            ViewData["InsuranceId"] = new SelectList(db.Insurances, "Id", "Name");
            return View();
        }

        // POST: Admin/Contract/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Beneficiary,Duration,CreatedAt,ExpiredAt,CustomerId,InsuranceId,Status,Total")] Contract contract)
        {

                db.Add(contract);
                await db.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
/*      
            ViewData["CustomerId"] = new SelectList(db.Customers, "Id", "Username", contract.CustomerId);
            ViewData["InsuranceId"] = new SelectList(db.Insurances, "Id", "Name", contract.InsuranceId);
            return View(contract);*/
        }

        // GET: Admin/Contract/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || db.Contracts == null)
            {
                return NotFound();
            }

            var contract = await db.Contracts.FindAsync(id);
            if (contract == null)
            {
                return NotFound();
            }
            ViewData["CustomerId"] = new SelectList(db.Customers, "Id", "Username", contract.CustomerId);
            ViewData["InsuranceId"] = new SelectList(db.Insurances, "Id", "Name", contract.InsuranceId);
            return View(contract);
        }

        // POST: Admin/Contract/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Beneficiary,Duration,CreatedAt,ExpiredAt,CustomerId,InsuranceId,Status,Total")] Contract contract)
        {
            if (id != contract.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    db.Update(contract);
                    await db.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContractExists(contract.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["CustomerId"] = new SelectList(db.Customers, "Id", "Username", contract.CustomerId);
            ViewData["InsuranceId"] = new SelectList(db.Insurances, "Id", "Name", contract.InsuranceId);
            return View(contract);
        }

        // GET: Admin/Contract/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || db.Contracts == null)
            {
                return NotFound();
            }

            var contract = await db.Contracts
                .Include(c => c.Customer)
                .Include(c => c.Insurance)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (contract == null)
            {
                return NotFound();
            }

            return View(contract);
        }

        // POST: Admin/Contract/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (db.Contracts == null)
            {
                return Problem("Entity set 'InsuranceOnlineContext.Contracts'  is null.");
            }
            var contract = await db.Contracts.FindAsync(id);
            if (contract != null)
            {
                db.Contracts.Remove(contract);
            }
            
            await db.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContractExists(int id)
        {
          return (db.Contracts?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

WebApp/Controllers/ContractsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Web;
using WebApp.Models;
using X.PagedList;

namespace WebApp.Controllers
{
    public class ContractsController : Controller
    {
        private InsuranceOnlineContext db = new InsuranceOnlineContext();
        public IActionResult Index(int? page)
        {
            
            var uid = HttpContext.Session.GetInt32("user_id");
            var u = db.Customers.FirstOrDefault(x => x.Id == uid);
            if (u != null)
            {
                var pageNumber = page ?? 1;
                var list_contract = db.Contracts.Where(x => x.CustomerId == uid).Include(x => x.Insurance.Category).Include(x => x.Insurance).Include(x => x.Payments).OrderBy(x=>x.Id).ToList();
                var list = list_contract.ToPagedList(pageNumber,6);
                ViewBag.List_Contract = list;
                ViewBag.Page = pageNumber;
                ViewBag.TotalPage = Math.Ceiling((double)list_contract.Count/6);
                return View();
            }
            else
            {
                return NotFound();
            }               
        }

        public ActionResult Detail(int id)
        {
            if(TempData["Msg"] != null)
            {
                ViewBag.Msg = TempData["Msg"];
            }
            var o = db.Contracts.FirstOrDefault(x => x.Id == id);
            if (o != null)
            {
                return View(o);
            }
            else
            {
                return RedirectToAction("", "Home");
            }
        }

        [HttpGet]
        public ActionResult Cancel(int id)
        {
            var o = db.Contracts.FirstOrDefault(x => x.Id == id);
            if (o != null)
            {
                o.Status = null;
                var stt = db.SaveChanges() > 0;
                if (stt)
                {
                    TempData["Msg"] = "Canceled the contract successfully!";
                }
                else
                {
                    TempData["Msg"] = "Error!";
                }                                  
            }
            else
            {
                TempData["Msg"] = "Error!";
                
            }
            return RedirectToAction("","Home");
        }

        [HttpGet]
        public ActionResult Pay(int id)
        {
            var o = db.Contracts.FirstOrDefault(x => x.Id == id);
            if (o != null)
            {
                var created_payment = db.Payments.FirstOrDefault(x=>x.ContractId==id);
                if (created_payment == null)
                {
                    var payment = new Payment
                    {
                        ContractId = id,
                        Total=0
                    };
                    db.Payments.Add(payment);
                    var stt = db.SaveChanges()>0;
                    if(!stt)
                    {
                        return BadRequest();
                    }
                    else
                    {
                        created_payment = payment;
                    }    
                }
                return View("Payment", created_payment);
            }
            else
            {
                return RedirectToAction("", "Home");
            }
        }

        [HttpPost]
        public ActionResult Pay(int ContractID, int PaymentID, decimal PaidAmount, string ContentDetails, int PeriodicID)
        {
            var o = db.Payments.FirstOrDefault(x => x.Id == PaymentID);
            if (o != null)
            {
                PaymentDetail e = new PaymentDetail
                {
                    ContentDetails = HttpUtility.UrlEncode(ContentDetails),
                    CreatedAt = DateTime.Now,
                    PaidAmount= PaidAmount,
                    PaymentId=PaymentID,
                    PeriodicId=PeriodicID
                };
                db.PaymentDetails.Add(e);
                var stt = db.SaveChanges() > 0;
                if (stt)
                {
                    /*var init = o.Total;
                    o.Total = init + e.PaidAmount;*/
                    db.SaveChanges();
                    TempData["Msg"] = "Paid successfully!";
                }
                else
                {
                    TempData["Msg"] = "Error";
                }
                return RedirectToAction("Detail","Contracts", new {id=ContractID});
            }
            else
            {
                return RedirectToAction("", "Home");
            }
        }
    }
}

WebApp/Areas/Admin/Views/Contract/Create.cshtml
@model WebApp.Models.Contract

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Create</h1>

<h4>Contract</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CustomerId" class="control-label">Customer</label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="InsuranceId" class="control-label">Insurance</label>
                <select asp-for="InsuranceId" class="form-control" asp-items="ViewBag.InsuranceId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Beneficiary" class="control-label"></label>
                <input asp-for="Beneficiary" class="form-control" />
                <span asp-validation-for="Beneficiary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" id="CreatedAt"/>
                <span asp-validation-for="ExpiredAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpiredAt" class="control-label"></label>
                <input asp-for="ExpiredAt" class="form-control" id="ExpiredAt"/>
                <span asp-validation-for="ExpiredAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label">Duration (Year)</label>
                <input asp-for="Duration" class="form-control" id="duration"/>
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select name="Status">
                    <option value="True" selected>Completed</option>
                    <option value="False">Maintaining</option>
                    <option value="Null">Cancelled</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>


@*<script>
$(document).ready(function(){
		var today = new Date();
		var date = today.getFullYear()+'-'+(today.getMonth()+1)+'-'+today.getDate();
		var time = today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds();
		var dateTime = date+' '+time;

		$("#Expired_at").val((today.getFullYear()+1)+'-'+(today.getMonth()+1)+'-'+today.getDate()+' '+today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds())
		$("#Created_at").val(dateTime)

		$("#duration").change(function(){
			var vl = Number($(this).val())
			var expired = new Date().getFullYear() + vl

			$("#Expired_at").val(expired+'-'+(today.getMonth()+1)+'-'+today.getDate()+' '+today.getHours() + ":" + today.getMinutes() + ":" + today.getSeconds())

			$("#total").val(3549999 * vl)

			if(vl==1)
				$("#y").text(vl+' Year')
			else
				$("#y").text(vl+' Years')


		})
})	

</script>*@

WebApp/Areas/Admin/Views/Contract/Delete.cshtml
@model WebApp.Models.Contract

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Contract</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Beneficiary)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Beneficiary)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Duration)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Duration)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreatedAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ExpiredAt)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ExpiredAt)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Customer)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Customer.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Insurance)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Insurance.Id)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

WebApp/Areas/Admin/Views/Contract/Details.cshtml
@model WebApp.Models.Contract

@{
    ViewData["Title"] = "Contract Details";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
    var db = new InsuranceOnlineContext();
}

<h1>Contract Details</h1>
<p style="padding: 15px;">
    <a href="@Url.Action("","Contract")" class="ta-btn">Back</a>
    @{
        if (Model.Status == false)
        {
            <a href="@Url.Action("Create","PaymentDetail", new {ContractId=Model.Id})" class="ta-btn">Add New Payment</a>
        }
    }
</p>
<div class="container">
    <div class="card">
        <div class="card-body">
            <div id="invoice" class="p-h-30">
                <div class="m-t-15 lh-2">
                    <div class="inline-block">
                        <address class="p-l-10">
                            @{
                                if (Model.Status == null)
                                {
                                    <span class="font-weight-semibold text-dark">Status: Cancelled</span>
                                }
                                else
                                                if (Model.Status == true)
                                {
                                    <span class="font-weight-semibold text-dark">Status: Completed</span>
                                }
                                else
                                {
                                    <span class="font-weight-semibold text-dark">Status: Maintaining</span>
                                }
                            }
                        </address>
                    </div>
                    <div class="float-right">
                        <h2>@Model.Insurance.Name</h2>
                    </div>
                </div>
                <div class="row m-t-20 lh-2">
                    <div class="col-sm-9">
                        <h3 class="p-l-10 m-t-10">Contract #NO@(Model.Id)</h3>
                        <address class="p-l-10 m-t-10">
                            <span class="font-weight-semibold text-dark">@Model.Customer.Username</span><br>
                            <span>@Model.Customer.Email</span><br>
                            <span>@Model.Customer.Address</span>
                        </address>
                    </div>
                    <div class="col-sm-3">
                        <div class="text-dark text-uppercase d-inline-block">
                            <span class="font-weight-semibold text-dark">Created Date :</span>
                        </div>
                        <div class="float-right">@Model.CreatedAt.Value.ToString("d")</div>
                        <div class="text-dark text-uppercase d-inline-block">
                            <span class="font-weight-semibold text-dark">Expired Date :</span>
                        </div>
                        <div class="float-right">@Model.ExpiredAt.Value.ToString("d")</div>
                    </div>
                </div>
                <div class="m-t-20">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>No.</th>
                                    <th>Content</th>
                                    <th>Month</th>
                                    <th>Paid Amount</th>
                                    <th>Total</th>
                                    @{
                                        if (Model.Status == null)

                                        {
                                            <th>Action</th>
                                        }
                                    }
                                </tr>
                            </thead>
                            <tbody>
                                @{
                                    var stt = 1;
                                    var _list = Model.Payments.First().PaymentDetails.ToList();
                                    if (_list != null && _list.Count > 0)
                                        foreach (var item in _list)
                                        {
                                            var m = db.PeriodicPaymentMethods.FirstOrDefault(x => x.Id == item.PeriodicId);
                                            <tr>
                                                <th>@(stt++)</th>
                                                <th>@item.ContentDetails</th>
                                                <th>@m.NumberOfMonth</th>
                                                <th>@((int)item.PaidAmount)</th>
                                                <th>@((int)item.PaidAmount)</th>
                                                @{
                                                    if (Model.Status != null)
                                                    {
                                                        <th>
                                                            <a href="@Url.Action("Edit","PaymentDetail", new {id=item.Id})">Edit</a> |
                                                            <a href="@Url.Action("Delete","PaymentDetail",new {id=item.Id,contractid=Model.Id})">Delete</a>
                                                        </th>
                                                    }
                                                }
                                            </tr>
                                        }
                                }
                            </tbody>
                        </table>
                    </div>
                    <div class="row m-t-30 lh-1-8">
                        <div class="col-sm-12">
                            <div class="float-right text-right">
                                @{
                                    decimal t = 0;
                                    var _l = db.PaymentDetails.Where(x=>x.PaymentId==Model.Payments.First().Id).ToList();
                                    if (_l != null && _l.Count>0)
                                    {
                                        foreach(var item in _l)
                                        {
                                            t = t + item.PaidAmount;
                                        }
                                    }
                                }
                                <p>Total paid amount: $@((int)t)</p>
                                <hr>
                                <h3><span class="font-weight-semibold text-dark">Total cost of this contract :</span> $@((int)Model.Total)</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

WebApp/Areas/Admin/Views/Contract/Edit.cshtml
@model WebApp.Models.Contract

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>Contract</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="All" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
             <div class="form-group">
                <label asp-for="CustomerId" class="control-label">Customer</label>
                <select asp-for="CustomerId" class="form-control" asp-items="ViewBag.CustomerId"></select>
            </div>
            <div class="form-group">
                <label asp-for="InsuranceId" class="control-label">Insurance</label>
                <select asp-for="InsuranceId" class="form-control" asp-items="ViewBag.InsuranceId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Beneficiary" class="control-label"></label>
                <input asp-for="Beneficiary" class="form-control" />
                <span asp-validation-for="Beneficiary" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedAt" class="control-label"></label>
                <input asp-for="CreatedAt" class="form-control" id="CreatedAt"/>
                <span asp-validation-for="ExpiredAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ExpiredAt" class="control-label"></label>
                <input asp-for="ExpiredAt" class="form-control" id="ExpiredAt"/>
                <span asp-validation-for="ExpiredAt" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Duration" class="control-label">Duration (Year)</label>
                <input asp-for="Duration" class="form-control" id="duration"/>
                <span asp-validation-for="Duration" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <select name="Status">
                    <option value="True" selected>Completed</option>
                    <option value="False">Maintaining</option>
                    <option value="Null">Cancelled</option>
                </select>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

WebApp/Areas/Admin/Views/Contract/Index.cshtml
@model IEnumerable<WebApp.Models.Contract>

@{
    ViewData["Title"] = "List";
    Layout = "~/Areas/Admin/Views/Shared/_Layout.cshtml";
}

<h1>List</h1>

<p>
    <a asp-action="Create" class="ta-btn">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Customer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Insurance)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Duration)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CreatedAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ExpiredAt)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Total)
            </th>

            <th>Action</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Customer.Username)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Insurance.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Duration) Years
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.CreatedAt)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.ExpiredAt)
                </td>
                <td>
                    @{
                        if (item.Status == null)
                        {
                            <span class="cancelled">Cancelled</span>
                        }
                        else
                        if (item.Status == true)
                        {
                            <span class="completed">Completed</span>
                        }
                        else
                        {
                            <span class="maintaining">Maintaining</span>
                        }
                    }
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Total)
                </td>

                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>